version : "3.9"

services:
  db:
    image: postgres:16
    container_name: weather_db
    environment:
      POSTGRES_DB: weather_db
      POSTGRES_USER: weather_user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    ports:
      - "5432:5432"

  redis:
    image: redis:8
    container_name: weather_redis
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: weather_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    depends_on:
      - db
      - redis

  celery_worker:
    build: .
    container_name: weather_celery_worker
    command: celery -A weather_stats worker --pool=solo --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env.docker
    depends_on:
      - db
      - redis

  celery_beat:
    build: .
    container_name: weather_celery_beat
    command: celery -A weather_stats beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env.docker
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
