# Generated by Django 5.2.4 on 2025-08-07 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='conditions',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='wind_speed',
            field=models.FloatField(null=True),
        ),
    ]
