# Generated by Django 5.2.4 on 2025-08-07 15:24

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_weatherdata_conditions_weatherdata_wind_speed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherdata',
            old_name='location',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='conditions',
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='cloudiness',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='feels_like',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='measured_at',
            field=models.DateTimeField(default=timezone.datetime(2023, 1, 1, tzinfo=timezone.get_current_timezone())),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='pressure',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='wind_speed',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
