# Generated by Django 5.2.4 on 2025-08-09 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_rename_location_weatherdata_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherdata',
            options={'ordering': ['-measured_at']},
        ),
    ]
